//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFModernVerticalMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public int IdCategorie { get; set; }
        public string CodeCategorie { get; set; }
        public string LibelleCategorie { get; set; }
    }
}
